/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  v1SideBar: [
    'v1/guide',
    'v1/smp',
    {
      type: 'category',
      label: 'Market',
      items: [
        {
          type: 'autogenerated',
          dirName: 'v1/market'
        }
      ]
    },
    {
      type: 'category',
      label: 'Trade',
      items: [
        {
          type: 'autogenerated',
          dirName: 'v1/order'
        }
      ]
    },

    {
      type: 'category',
      label: 'Account',
      items: [
        {
          type: 'autogenerated',
          dirName: 'v1/account'
        }
      ]
    },
    {
      type: 'category',
      label: 'Asset',
      items: [
        'v1/asset/coin-info',
        'v1/asset/sub-uid-list',
        {
          type: 'category',
          label: 'Balances',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v1/asset/balance'
            }
          ]
        },
        {
          type: 'category',
          label: 'Transfer',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v1/asset/transfer'
            }
          ]
        },
        {
          type: 'category',
          label: 'Deposit',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v1/asset/deposit'
            }
          ]
        },
        {
          type: 'category',
          label: 'Withdraw',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v1/asset/withdraw'
            }
          ]
        },
        // {
        //   type: 'category',
        //   label: 'Convert',
        //   items: [
        //     {
        //       type: 'autogenerated',
        //       dirName: 'v1/asset/convert'
        //     }
        //   ]
        // }
      ]
    },
    // {
    //   type: 'category',
    //   label: 'User',
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'v1/user'
    //     }
    //   ]
    // },





    {
      type: 'category',
      label: 'Fiat',
      items: [
        'v1/fiat/bank-accounts',
        {
          type: 'category',
          label: 'Withdraw',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v1/fiat/withdrawals'
            }
          ]
        }
      ]
    },

    {
      type: 'category',
      label: 'WebSocket Stream',
      items: [
        'v1/websocket/wss-authentication',
        {
          type: 'category',
          label: 'Public',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v1/websocket/public'
            }
          ]
        },
        {
          type: 'category',
          label: 'Private',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v1/websocket/private'
            }
          ]
        },
        {
          type: 'category',
          label: 'Trade',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v1/websocket/trade'
            }
          ]
        }

      ]
    },
    {
      type: 'category',
      label: 'Rate Limit',
      items: [
        'v1/rate-limit/rate-limit',
        'v1/rate-limit/rules-for-vips',
        {
          type: 'category',
          label: 'API Rate Limit Rules for PROs',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v1/rate-limit/rules-for-pros'
            }
          ]
        },
      ]
    },
    'v1/enum',
    'v1/error',
  ],
  // apiExplorerSideBar: [
  //   {
  //     type: "category",
  //     label: "V5",
  //     link: {
  //       type: "generated-index",
  //       title: "V5 API",
  //       slug: "/api-explorer/v1/category/"
  //     },
  //     // @ts-ignore
  //     items: [
  //       require("./docs/api-explorer/v1/market/sidebar.js"),
  //       require("./docs/api-explorer/v1/trade/sidebar.js"),
  //       require("./docs/api-explorer/v1/account/sidebar.js"),
  //       require("./docs/api-explorer/v1/asset/sidebar.js"),
  //       require("./docs/api-explorer/v1/user/sidebar.js"),
  //       require("./docs/api-explorer/v1/lt/sidebar.js"),
  //       require("./docs/api-explorer/v1/spot-margin-uta/sidebar.js"),
  //     ]
  //   }
  // ],
  changelogSidebar: [
    "changelog/v1"
  ]
};

module.exports = sidebars;
